### ISSUE TITLE
TypeError in method process_single_csv

### ISSUE THREAD

**Issue by nmiranda** [supernnova/SuperNNova#1]
Line 473 of make_dataset.py reads:
```python
for c_ in [2, list(set(len(settings.sntypes.keys())))]:
```

This is currently throwing the following error:
> TypeError: 'int' object is not iterable

This will always happen, as method `len` always returns an `int` type.

**Comment by nmiranda** [comment]
It seems that branch `experiments` has a fix for this bug.

**Comment by anaismoller** [comment]
Thanks for logging an issue, indeed, the experiment branch had the solution. The latest commit fixes this error.
The experiment branch will soon be merged and will provide a CNN architecture as well. 
¡Gracias!
