### ISSUE TITLE
Unusual results for PS1 Data

### ISSUE THREAD

**Issue by bap37** [supernnova/SuperNNova#19]
As discussed on Slack - When fitting PS1 data (HEAD and PHOT files in here $PS1_ROOT/lcmerge/PS1_PS1MD_cen_SIGCLIP_FITS/ ) we get some weird results - only 450 SNe in the sample are classified as Ia, and this seems to be entirely random. A couple spectroscopically confirmed SNIa are being listed as 100% chance CC, so something's up. I generated some SNN example plots using the following command :

/scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-DATA/3_CLAS/old-PS1/job_plot.slurm

and in general the relevant directory is here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-DATA/3_CLAS/SNNTEST_PS_DATAPS1_SNNTEST_PS_PS1+MVCC

**Comment by bap37** [comment]
you may notice that in $PIPPIN_OUTPUT/PANOPTICON-DATA/3_CLAS/ there's an "old-PS1" and the regular one - I was really hoping this was a random glitch, so I copied the original directory to "old-PS1" and reran. They should be identical, at least predictions.csv was!

**Comment by anaismoller** [comment]
Good catch Brodie! Issue was the the PS1 photometry is not sorted by ascending time for a given event (as it would be from observations). I have added a failsafe to address this so not sorting necessary. Please let me know if there are other issues
