### ISSUE TITLE
Function pivot_dataframe_batch is not handling concurrent exceptions (fails silently)

### ISSUE THREAD

**Issue by nmiranda** [supernnova/SuperNNova#2]
In `make_dataset.py`, lines 696-701 read:
```python
    for chunk_idx in tqdm(list_chunks, desc="Pivoting dataframes", ncols=100):
        parallel_fn = partial(pivot_dataframe_single, settings=settings)
        # Process each file in the chunk in parallel
        with ProcessPoolExecutor(max_workers=max_workers) as executor:
            start, end = chunk_idx[0], chunk_idx[-1] + 1
            executor.map(parallel_fn, list_files[start:end])
```
The iterator with results of the execution of the `map` function is not being accessed at any time afterwards. Unfortunately, this has as a side effect that, if any of the executors fail, the corresponding exception is never going to be raised, and, therefore, it will fail silently. (See https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.map )

**Comment by anaismoller** [comment]
SuperNNova is released for production and therefore our goal is to speed up processing (mapping allows this). If you want to debug, there is commented lines below that you can use for this.

**Comment by nmiranda** [comment]
Thank you very much for the reply!

I think one thing doesn't exclude the other. From what I understand, one can run the processes in parallel with map, and then, once they are ready, one can access them and see if any of the child processes ended with an exception. For that it is only needed to save the results of the map function and then access them; like this, for instance:
```python
results = executor.map(parallel_fn, list_files[start:end])
for n, pid in results:
    logging_utils.print_yellow('ran task {} in process {}'.format(n, pid))
```

However, if you prefer to keep it as it is, I think it would be a good improvement to add a `--debug` flag to execute without using multiprocessing; instead of commenting and uncommenting lines of code.

Best regards!
