### ISSUE TITLE
PS1 classification issues 

### ISSUE THREAD

**Issue by bap37** [supernnova/SuperNNova#21]
Morning! 

After you fixed the plotting issue from yesterday, I went and reclassified the PS1 data. We were seeing only 450 SNe pass as SNN-classified type Ia, and most of the spectroscopically confirmed Ia were marked as 100% CC by SNN. This hasn't changed since the update pushed yesterday, and we are a bit lost.  (to be clear - I did not re-train a model, just re-used the same model on the data again after the update).

I've sent some pictures on slack that I hope demonstrate the problem, and the relevant directories are here:

This is where the PS1 training set was generated and trained:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-PS1-CLASS/
This is where it was used to fit the PS1 data:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-DATA/
And tested on simulated PS1 data here:
/scratch/midway2/rkessler/PIPPIN_OUTPUT/BP-PS1-CLASSTEST/

I remade the light-curve plots, they live here: /scratch/midway2/rkessler/PIPPIN_OUTPUT/PANOPTICON-DATA/3_CLAS/SNNTEST_PS_DATAPS1_SNNTEST_PS_PS1+MVCC/dump/lightcurves/SNNTEST_PS_PS1+MVCC/early_prediction

They look good now!

**Comment by bap37** [comment]
It was a pippin issue! SNN looks good now!

**Comment by bap37** [comment]
we're fitting about 50% of the PS1-spectroscopically confirmed SNIa as CC. Pretty similar for SDSS. Is this normal?

**Comment by bap37** [comment]
Having a similar but separate issue for the spec sample. We couldn't get the plot_file working, as above, so we tried to run SNN on the spec sample as analogue to see the plots. Unfortunately, we're getting a strange error when running 

/scratch/midway2/rkessler/PIPPIN_OUTPUT/MV_PS1_SDSS/3_CLAS/SNNTEST_PS_DATAPS1_SNNTEST_PS_PS1+MVCC/job_plot.slurm

which is detailed in /scratch/midway2/rkessler/PIPPIN_OUTPUT/MV_PS1_SDSS/3_CLAS/SNNTEST_PS_DATAPS1_SNNTEST_PS_PS1+MVCC/output.log - 

^[[32m[Computing splits] ^[[0m                                                                                                                
List files []                                                                                                                                 
                                                                                                                                              
^[[32m[Data processing] ^[[0m<0s                                                                                                              
Traceback (most recent call last):                                                                                                            
  File "run.py", line 210, in <module>                                                                                                        
    raise e                                                                                                                                   
  File "run.py", line 44, in <module>                                                                                                         
    make_dataset.make_dataset(settings)                                                                                                       
  File "/project2/rkessler/PRODUCTS/miniconda/envs/snn_gpu/lib/python3.6/contextlib.py", line 52, in inner                                    
    return func(*args, **kwds)                                                                                                                
  File "/project2/rkessler/PRODUCTS/classifiers/supernnova/supernnova/data/make_dataset.py", line 814, in make_dataset                        
    build_traintestval_splits(settings)                                                                                                       
  File "/project2/rkessler/PRODUCTS/classifiers/supernnova/supernnova/data/make_dataset.py", line 96, in build_traintestval_splits            
    df_photo = pd.concat(list_df)                                                                                                             
  File "/project2/rkessler/PRODUCTS/miniconda/envs/snn_gpu/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 225, in concat    
    copy=copy, sort=sort)                                                                                                                     
  File "/project2/rkessler/PRODUCTS/miniconda/envs/snn_gpu/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 259, in __init__  
    raise ValueError('No objects to concatenate')                                                                                             
ValueError: No objects to concatenate   

This seems to be arising from the photo_window_files, but I haven't been able to figure out what the problem is

**Comment by anaismoller** [comment]
.txt format is not supported with SuperNNova, only .FITS (SNANA format) or .csv (Plasticc format)
