### ISSUE TITLE
AttributeError: 'ExperimentSettings' object has no attribute 'sntype_var'

### ISSUE THREAD

**Issue by JulienPeloton** [supernnova/SuperNNova#24]
Using the branch `elasticc`, the code used to process ZTF fails with error:

```
File "fink_science/snn/processor.py", line 167, in snn_ia
    ids, pred_probs = classify_lcs(pdf, model, 'cpu')
  File "/home/libs/miniconda/lib/python3.7/site-packages/supernnova/validation/validate_onthefly.py", line 99, in classify_lcs
    df = format_data(df, settings)
  File "/home/libs/miniconda/lib/python3.7/site-packages/supernnova/validation/validate_onthefly.py", line 59, in format_data
    df = pivot_dataframe_single_from_df(df, settings)
  File "/home/libs/miniconda/lib/python3.7/site-packages/supernnova/data/make_dataset.py", line 722, in pivot_dataframe_single_from_df
    + class_columns
AttributeError: 'ExperimentSettings' object has no attribute 'sntype_var'
```

Any ideas?

**Comment by JulienPeloton** [comment]
The code used here (which works with the master branch) can be found at:
https://github.com/astrolabsoftware/fink-science/blob/89781b769654487d7d96cfc2ee6ade885af0b435/fink_science/snn/processor.py#L77

**Comment by JulienPeloton** [comment]
Ah -- if I understand correctly, the settings (https://github.com/supernnova/SuperNNova/blob/75d047cb361aaa6b36a9cfd02c65365622275ef9/supernnova/validation/validate_onthefly.py#L15) reads information from `args_cli.json`. For ZTF models, there was no `sntype_var`, while now for elasticc this variable seems mandatory. Could you either provide an update of the previous models' json files, or handle this exception in the code?

**Comment by anaismoller** [comment]
Should be fixed now for backward compatibility with pre-trained models in the main branch
