### ISSUE TITLE
Allow the user to define filter labels in pivot_dataframe_single

### ISSUE THREAD

**Issue by nmiranda** [supernnova/SuperNNova#3]
In file `make_dataset.py`, line 558 reads:
```python
list_filters = data_utils.FILTERS
```
Maybe it should instead say:
```python
list_filters = settings.list_filters
```
This would allow the user to define what filters to use and the label they have in the input table.

**Comment by anaismoller** [comment]
it is now an option. Remember to add as well the possible filter permutations. See documentation here: https://supernnova.readthedocs.io/en/latest/data/index.html

**Comment by nmiranda** [comment]
Thanks! That looks great!
